### ISSUE TITLE
PHPUnit Test Error Privacy Provider

### ISSUE THREAD

**Issue by almadog** [marcusgreen/local_read_only#8] opened 2021-03-10 16:37 UTC
Moodle 3.5.17
Local_read_only - master @ a05707f

The following phpunit tests error has been identified:

provider_testcase::test_all_providers_compliant with data set "local_read_only" ('local_read_only', 'local_read_only\privacy\provider')
    Failed asserting that false is true.
  
    /var/www/html/privacy/tests/provider_test.php:178
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80
  
    To re-run:
     vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php

**Comment by marcusgreen** [comment] 2021-04-01 08:55
Could you explain further. PHPUnit tests should not work at all if you have this installed and configured, and 'local_read_only\privacy\provider does not exist

**Comment by almadog** [comment] 2021-09-17 09:24
Sorry for late reply. 

We run phpunit as part of our CICD pipeline so it is run in the backend before we have a running Moodle instance. It is where this error is coming up.

**Comment by marcusgreen** [comment] 2021-09-17 10:01
I don't understand. If you have read-only correctly installed during unit tests then just about all tests should fail "by design". I may have mis-interpreted your question, so could you explain further.

**Comment by aspark21** [comment] 2021-09-29 15:36
Hi Marcus,

That's a simple one, it's a catch all in core for any 3rd party plugins which don't declare what personal information they store.

https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_store_content_in_a_Moodle_subsystem

A lot of plugins just declare they don't store anything themselves like this - https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/privacy/provider.php (+add language string for that in your plugin)

Al

**Comment by marcusgreen** [comment] 2021-09-29 15:42
Under what circumstances would such code be executed? I could add one but I am curious as to the benefit.

**Comment by marcusgreen** [comment] 2021-10-10 10:24
Because this plugin is designed to make the system read-only almost all (every?) unit test should fail. 
This is why I created this
https://github.com/marcusgreen/local_read_only/blob/master/tests/dbtest.php
Let me know if I have missed something and/or if you have some code that will make the problem go away for you.
Closing on the basis it is working as designed.

**Closed as completed by marcusgreen** 2021-10-10 10:24 UTC
