### ISSUE TITLE
Issues with total marks in Moodle quiz

### ISSUE THREAD

**Issue by almadog** [marcusgreen/local_read_only#9] opened 2021-09-17 09:50 UTC
Moodle 3.9.8
local_read_only commit @ a05707f

- The read-only plugin is disabled from the front end.
- include_once(__DIR__.'/local/read_only/db.php'); is present in config.php

We have noticed that when updating the marks in a Moodle quiz the total of marks was not updated. In order to get this working we had to comment out the line in config.php above.

![image](https://user-images.githubusercontent.com/114595/133760253-d8e56ee8-0981-4872-9c7b-7271e34a39d9.png)

**Comment by marcusgreen** [comment] 2021-09-17 09:59
I don't understand, the local_readonly plugin is designed to discard updates and so would by design discard quiz updates. If you disable that line the site would no longer be read-only. Could you explain further.

**Comment by marcusgreen** [comment] 2021-10-10 10:18
I am closing this on the basis that it appears to ask why setting the system to read-only results in the system discarding updates. It appears to be working as designed.

**Closed as completed by marcusgreen** 2021-10-10 10:18 UTC
